### ISSUE TITLE
backup_upload_connection doesn`t support endpoint

### ISSUE THREAD

**Issue by patsevanton** [robertdebock/ansible-role-gitlab#6]
Thanks for role gitlab
I try backup to Digital Ocean Spaces S3 

https://docs.gitlab.com/ee/raketasks/backup_restore.html#digital-ocean-spaces

But gitlab_rails_backup_upload_connection don`t have endpoint.
May be add endpoint to readme.

**Comment by robertdebock** [comment]
Hi, thanks for your input, should be an easy one to add. Give me some time to add it, test it and release a new version.

**Comment by robertdebock** [comment]
Hi,

That's included in version 1.10.0. Please try it and see if it works for you, thanks again!

Robert.
